name: Publish crl/dicom-tools container image
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  publish-dicom-tools-image:
    runs-on: ubuntu-latest
    name: Publish a container image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
             
      - name: Log in to the Github container registry
        uses: docker/login-action@v3
        with: 
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
       
      - name: Extract metadata for Docker
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                
