name: publish
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
publish-dicom-tools-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build and publish the crl/dicom-tools image
run: |
  docker build . --file Dockerfile --tag crl/dicom-tools:$(date +%s)
  docker run crl/dicom-tools:latest
  docker push crl/dicom-tools:latest
  
